import {
  bdyDatePickerAbc,
  bdyVerticalCardAbc,
  mdListPickerAbc,
  mdDatePickerAbc,
  bdyListPickerAbc,
  bdyVerticalCardOnlyImageAbc,
  bdyVerticalCardOnlyButtonAbc,
  bdyVerticalCardTwoButtonsAbc,
  bdyVerticalCardTwoImagesAbc,
  bdyListPickerOneOptionAbc,
  mdListPickerOneOptionAbc,
  bdyListPickerMultipleOptionsAbc,
  mdListPickerMultipleOptionsAbc,
  bdyListPickerWithoutImagesAbc,
  mdListPickerWithoutImagesAbc,
  bdyListPickerWithImagesAbc,
  mdListPickerWithImagesAbc,
  bdyListPickerWithoutButtonsAbc,
  mdListPickerWithoutButtonsAbc,
  mdUndefinedReceivedReplyMessagesAbc,
  mdNoReceivedReplyMessagesAbc,
  bdyListPickerMultiSelectAbc,
  mdListPickerMultiSelectAbc,
  bdyListPickerMultiSelectPerSectionAbc,
  mdListPickerMultiSelectPerSectionAbc,
  bdyListPickerMultiOptionsPerSectionAbc,
  mdListPickerMultiOptionsPerSectionAbc,
  bdyCustomMessag1eAbc,
  mdCustomMessage1Abc,
  bdyCustomMessage2Abc,
  mdCustomMessage2Abc,
  bdyCustomMessage3Abc,
  mdCustomMessage3Abc,
  bdyListPickerLargeAbc,
  mdListPickerLargeAbc,
  bdyDatePickerOneOptionAbc,
  mdDatePickerOneOptionAbc,
  bdyDatePickerMoreOptionsAbc,
  mdDatePickerMoreOptionsAbc,
  bdyDatePickerPastDateAbc,
  bdyAuthenticationAbc,
  mdAuthenticationAbc,
  mdAuthenticationWithImageAbc,
  mdAuthenticationWithResponseEncryptionKeyAbc,
  bdyApplePayAbc,
  mdApplePayAbc,
  bdyListPickerButtonMissingTitleAbc,
  bdyListPickerMissingEntryDefTitleAbc,
  bdyListPickerMissingEntryDefButtonAbc,
  bdyListPickerMissingEntryDefSubtitleAbc,
  bdyQuickReplyAbc,
  expectedSchemaBodyAbc,
  expectedSchemaMetadataAbc,
  expectedSchemaQuickReplyAbc,
  mdFormAbc,
  mdCBBotResponseAbc,
  mdBotResponseAbc,
  bdyFormAbc,
  mdCbAutoMessage,
} from './abcHelper';

import {
  bdyCarouselComplexLine,
  bdyVerticalCardLine,
  qrQuickRepliesTextOnlyLine,
  qrQuickRepliesWithEmojisLine,
  bdyCardWithoutImageOrTitleLine,
  bdyCardWithTooLongSubtitle1Line,
  bdyCardWithTooLongSubtitle2Line,
  bdyCardWithImageTitleSubtitleLine,
  bdyCardWorkingLine,
  bdyCardWith4ButtonsLine,
  bdyCardWith5ButtonsLine,
  bdyCarouselWith4ButtonCardsLine,
  bdyCarouselWith2ButtonCardsLine,
  bdyCarouselWith3ButtonCardsLine,
  bdyCarouselWithoutImageAndTitleLine,
  bdyCarouselWith11CardsLine,
  bdyCarouselWith10CardsLine,
  bdyCarouselRandom1Line,
  bdyCarouselRandom2Line,
  bdyCardWithDisplayPropertyLine,
  bdyCarouselWithDisplayPropertyLine,
  bdyCardWithWrongDisplayPropertyLine,
  bdyCarouselWithWrongDisplayPropertyLine,
  expectedSchemaBodyLine,
  expectedSchemaMetadataLine,
  expectedSchemaQuickrepliesLine,
} from './lineHelper';

import {
  qrQuickReplyStyledWeb,
  bdyMultipleChecklistComponentWeb,
  bdyCarouselComplexWeb,
  bdyCarouselBasicWeb,
  bdyVerticalCardWeb,
  bdyButtonWeb,
  bdyImageWeb,
  bdyMapWeb,
  bdyTextWeb,
  bdyHorizontalCardWeb,
  expectedSchemaBodyWeb,
  expectedSchemaMetadataWeb,
  expectedSchemaQuickrepliesWeb,
} from './webHelper';

import {
  qrQuickRepliesSpecialCharactersRbm,
  qrQuickReplies11ButtonsRbm,
  qrQuickReplies12ButtonsRbm,
  qrQuickReply26CharsRbm,
  qrQuickReply25CharsRbm,
  bdyVerticalCardRbm,
  bdyHorizontalCardRbm,
  bdyVerticalCardTooLongButtonRbm,
  bdyHorizontalCardTooLongButtonRbm,
  bdyHorizontalCardWithoutImageRbm,
  bdyVerticalCardWithoutImageRbm,
  bdyHorizontalCardWithoutTitleOrSubtitleRbm,
  bdyVerticalCardWithoutTitleOrSubtitleRbm,
  bdyHorizontalCardTooManyButtonsRbm,
  bdyVerticalCardTooManyButtonsRbm,
  bdyCarousel10CardsRbm,
  bdyCarousel11CardsRbm,
  expectedSchemaBodyRbm,
  expectedSchemaMetadataRbm,
  expectedSchemaQuickrepliesRbm,
} from './rbmHelper';

import {
  bdyVerticalCardViber,
  bdyVerticalCardViberOver7Elements,
  bdyVerticalCarouselViber,
  bdyVerticalCarouselViber11Cards,
  bdyVerticalCarouselViberNoCards,
  bdyVerticalCardViberWithButtonStyling,
  expectedSchemaBodyViber,
  expectedSchemaMetadataViber,
  expectedSchemaQuickrepliesViber,
} from './viberHelper';

import {
  expectedSchemaBodyWhatsApp,
  expectedSchemaMetadataWhatsApp,
  expectedSchemaQuickrepliesWhatsApp,
  bdyWhatsAppSingleProductJson,
  mdWhatsAppSingleProductMetadata,
  bdyWhatsAppMultiProductJson,
  mdWhatsAppMultiProductMetadata,
} from './whatsappHelper';

import { fbJsonContainers, expectedSchemaBodyFb, expectedSchemaMetadataFb, expectedSchemaQuickrepliesFb } from './fb';
import {
  twitterJsonContainers,
  expectedSchemaMetadataTwitter,
  expectedSchemaBodyTwitter,
  expectedSchemaQuickrepliesTwitter,
} from './twitter';
import {
  instagramJsonContainers,
  expectedSchemaMetadataInstagram,
  expectedSchemaBodyInstagram,
  expectedSchemaQuickrepliesInstagram,
} from './instagram';
import { gbmJsonContainers, expectedSchemaBodyGbm, expectedSchemaMetadataGbm, expectedSchemaQuickrepliesGbm } from './gbm';
import { Channels } from '../../src';
import { Types } from '../../src/types';

export const testJsonContainers = [
  ...fbJsonContainers,
  ...twitterJsonContainers,
  ...instagramJsonContainers,
  ...gbmJsonContainers,

  qrQuickReplyStyledWeb,
  bdyMultipleChecklistComponentWeb,
  bdyCarouselComplexWeb,
  bdyCarouselBasicWeb,
  bdyVerticalCardWeb,
  bdyButtonWeb,
  bdyImageWeb,
  bdyMapWeb,
  bdyTextWeb,
  bdyHorizontalCardWeb,

  bdyCarouselComplexLine,
  bdyVerticalCardLine,
  qrQuickRepliesTextOnlyLine,
  qrQuickRepliesWithEmojisLine,
  bdyCardWithoutImageOrTitleLine,
  bdyCardWithTooLongSubtitle1Line,
  bdyCardWithTooLongSubtitle2Line,
  bdyCardWithImageTitleSubtitleLine,
  bdyCardWorkingLine,
  bdyCardWith4ButtonsLine,
  bdyCardWith5ButtonsLine,
  bdyCarouselWith4ButtonCardsLine,
  bdyCarouselWith2ButtonCardsLine,
  bdyCarouselWith3ButtonCardsLine,
  bdyCarouselWithoutImageAndTitleLine,
  bdyCarouselWith11CardsLine,
  bdyCarouselWith10CardsLine,
  bdyCardWithDisplayPropertyLine,
  bdyCarouselWithDisplayPropertyLine,
  bdyCarouselRandom1Line,
  bdyCarouselRandom2Line,
  bdyCardWithWrongDisplayPropertyLine,
  bdyCarouselWithWrongDisplayPropertyLine,

  qrQuickRepliesSpecialCharactersRbm,
  qrQuickReplies11ButtonsRbm,
  qrQuickReplies12ButtonsRbm,
  qrQuickReply26CharsRbm,
  qrQuickReply25CharsRbm,
  bdyVerticalCardRbm,
  bdyHorizontalCardRbm,
  bdyVerticalCardTooLongButtonRbm,
  bdyHorizontalCardTooLongButtonRbm,
  bdyHorizontalCardWithoutImageRbm,
  bdyVerticalCardWithoutImageRbm,
  bdyHorizontalCardWithoutTitleOrSubtitleRbm,
  bdyVerticalCardWithoutTitleOrSubtitleRbm,
  bdyHorizontalCardTooManyButtonsRbm,
  bdyVerticalCardTooManyButtonsRbm,
  bdyCarousel10CardsRbm,
  bdyCarousel11CardsRbm,

  mdFormAbc,
  mdCBBotResponseAbc,
  mdBotResponseAbc,
  mdCbAutoMessage,
  bdyFormAbc,
  bdyDatePickerAbc,
  bdyVerticalCardAbc,
  bdyVerticalCardOnlyImageAbc,
  bdyVerticalCardOnlyButtonAbc,
  bdyVerticalCardTwoButtonsAbc,
  bdyVerticalCardTwoImagesAbc,
  mdListPickerAbc,
  mdDatePickerAbc,
  bdyListPickerButtonMissingTitleAbc,
  bdyListPickerMissingEntryDefTitleAbc,
  bdyListPickerMissingEntryDefButtonAbc,
  bdyListPickerMissingEntryDefSubtitleAbc,
  bdyListPickerAbc,
  bdyListPickerOneOptionAbc,
  mdListPickerOneOptionAbc,
  bdyListPickerMultipleOptionsAbc,
  mdListPickerMultipleOptionsAbc,
  bdyListPickerWithoutImagesAbc,
  mdListPickerWithoutImagesAbc,
  bdyListPickerWithImagesAbc,
  mdListPickerWithImagesAbc,
  bdyListPickerWithoutButtonsAbc,
  mdListPickerWithoutButtonsAbc,
  mdUndefinedReceivedReplyMessagesAbc,
  mdNoReceivedReplyMessagesAbc,
  bdyListPickerMultiSelectAbc,
  mdListPickerMultiSelectAbc,
  bdyListPickerMultiSelectPerSectionAbc,
  mdListPickerMultiSelectPerSectionAbc,
  bdyListPickerMultiOptionsPerSectionAbc,
  mdListPickerMultiOptionsPerSectionAbc,
  bdyCustomMessag1eAbc,
  mdCustomMessage1Abc,
  bdyCustomMessage2Abc,
  mdCustomMessage2Abc,
  bdyCustomMessage3Abc,
  mdCustomMessage3Abc,
  bdyListPickerLargeAbc,
  mdListPickerLargeAbc,
  bdyDatePickerOneOptionAbc,
  mdDatePickerOneOptionAbc,
  bdyDatePickerMoreOptionsAbc,
  mdDatePickerMoreOptionsAbc,
  bdyDatePickerPastDateAbc,
  bdyAuthenticationAbc,
  mdAuthenticationAbc,
  mdAuthenticationWithImageAbc,
  mdAuthenticationWithResponseEncryptionKeyAbc,
  bdyApplePayAbc,
  mdApplePayAbc,
  bdyQuickReplyAbc,

  bdyVerticalCardViber,
  bdyVerticalCardViberOver7Elements,
  bdyVerticalCarouselViber,
  bdyVerticalCarouselViberNoCards,
  bdyVerticalCarouselViber11Cards,
  bdyVerticalCardViberWithButtonStyling,

  bdyWhatsAppSingleProductJson,
  mdWhatsAppSingleProductMetadata,
  bdyWhatsAppMultiProductJson,
  mdWhatsAppMultiProductMetadata,
];

export const expectedSchemas = {
  [Channels.ABC]: {
    [Types.BDY]: expectedSchemaBodyAbc,
    [Types.MTD]: expectedSchemaMetadataAbc,
    [Types.QUR]: expectedSchemaQuickReplyAbc,
  },
  [Channels.FB]: {
    [Types.BDY]: expectedSchemaBodyFb,
    [Types.MTD]: expectedSchemaMetadataFb,
    [Types.QUR]: expectedSchemaQuickrepliesFb,
  },
  [Channels.TWITTER]: {
    [Types.BDY]: expectedSchemaBodyTwitter,
    [Types.MTD]: expectedSchemaMetadataTwitter,
    [Types.QUR]: expectedSchemaQuickrepliesTwitter,
  },
  [Channels.INSTAGRAM]: {
    [Types.BDY]: expectedSchemaBodyInstagram,
    [Types.MTD]: expectedSchemaMetadataInstagram,
    [Types.QUR]: expectedSchemaQuickrepliesInstagram,
  },
  [Channels.LINE]: {
    [Types.BDY]: expectedSchemaBodyLine,
    [Types.MTD]: expectedSchemaMetadataLine,
    [Types.QUR]: expectedSchemaQuickrepliesLine,
  },
  [Channels.RBM]: {
    [Types.BDY]: expectedSchemaBodyRbm,
    [Types.MTD]: expectedSchemaMetadataRbm,
    [Types.QUR]: expectedSchemaQuickrepliesRbm,
  },
  [Channels.WEB]: {
    [Types.BDY]: expectedSchemaBodyWeb,
    [Types.MTD]: expectedSchemaMetadataWeb,
    [Types.QUR]: expectedSchemaQuickrepliesWeb,
  },
  [Channels.GBM]: {
    [Types.BDY]: expectedSchemaBodyGbm,
    [Types.MTD]: expectedSchemaMetadataGbm,
    [Types.QUR]: expectedSchemaQuickrepliesGbm,
  },
  [Channels.VIBER]: {
    [Types.BDY]: expectedSchemaBodyViber,
    [Types.MTD]: expectedSchemaMetadataViber,
    [Types.QUR]: expectedSchemaQuickrepliesViber,
  },
  [Channels.WA]: {
    [Types.BDY]: expectedSchemaBodyWhatsApp,
    [Types.MTD]: expectedSchemaMetadataWhatsApp,
    [Types.QUR]: expectedSchemaQuickrepliesWhatsApp,
  },
};
